image:
  repository: "${apm_image}"
  tag: "${apm_image_tag}"
  pullPolicy: Always
  pullSecrets: []

apm:
  api_key: ${elastic_apm_key}
  namespaces: ${jsonencode(apm_target_namespaces)}

webhookConfig:
  agents:
    java:
      environment:
        ELASTIC_APM_SERVER_URL: "${apm_server_url}"
        ELASTIC_APM_ENVIRONMENT: "${apm_env}"
        ELASTIC_APM_LOG_LEVEL: "info"
        ELASTIC_APM_APPLICATION_PACKAGES: "${apm_application_packages}"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
    nodejs:
      environment:
        ELASTIC_APM_SERVER_URL: "${apm_server_url}"
        ELASTIC_APM_ENVIRONMENT: "${apm_env}"
        ELASTIC_APM_LOG_LEVEL: "info"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

  tolerations:
    - key: "apm-attacher"
      operator: "Exists"
      effect: "NoSchedule"

  nodeSelector:
    "kubernetes.io/os": "linux"
