config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 2000
    batch: {}

  exporters:
    debug:
      verbosity: detailed
    otlp/elastic:
      endpoint: ${elastic_apm_endpoint}  # Elastic APM server URL without "https://"
      headers:
        Authorization: "Bearer ${elastic_apm_enrollment_token}"  # Elastic APM server secret token

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug, otlp/elastic]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug, otlp/elastic]
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug, otlp/elastic]
image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: "Always"
mode: "daemonset"
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"
