roles: kube,app,discovery,db
databases:
%{~ for db in databases }
- name: "${db.name}"
  description: ${db.description}
  protocol: "${db.protocol}"
  uri: "${db.uri}"
  static_labels:
%{~ for key, value in db.labels }
    ${key}: "${value}"
%{~ endfor }
%{~ endfor }
authToken: ${eks_cluster_name}
proxyAddr: ${teleport_proxy_addr}
kubeClusterName: ${eks_cluster_name}
kubernetesDiscovery:
- types: ["app"]
  namespaces:
%{~ for ns in app_namespaces }
    - "${ns}"
%{~ endfor }
labels:
    env: ${env}
enterprise: true
updater:
    enabled: true
    releaseChannel: "stable/cloud"
highAvailability:
    replicaCount: ${replica_count}
    podDisruptionBudget:
        enabled: true
        minAvailable: ${pdb_min_available}
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

