apiVersion: v1
kind: Namespace
metadata:
  name: petclinic-linkerd
  labels:
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: infrastructure
    service-mesh: linkerd
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic-istio
  labels:
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: infrastructure
    service-mesh: istio
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic-cilium
  labels:
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: infrastructure
    service-mesh: cilium
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
